package com.magube.neuralsnek.snake;

import java.awt.event.KeyEvent;

public class SnakeGame extends javax.swing.JFrame {
    private final int telaH = 480;
    private final int telaW = 700;
    
    private final int blockSize = 20;
    
    private GameThread gameThread;
    
    public SnakeGame() {
        initComponents();
        tela.setTelaH(telaH);
        tela.setTelaW(telaW);
        
        gameThread = new GameThread(tela, telaW, telaH, blockSize);
        gameThread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tela = new com.magube.neuralsnek.snake.JTela();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Snake");
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);
        telaLayout.setHorizontalGroup(
            telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        telaLayout.setVerticalGroup(
            telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        //Quando viene premuta una freccia
        switch(evt.getKeyCode()) {
            case KeyEvent.VK_W:
                //Va in alto
                gameThread.moveSnake(0);
                break;
                
            case KeyEvent.VK_D:
                //Va a destra
                gameThread.moveSnake(1);
                break;
                
            case KeyEvent.VK_S:
                //Va in basso
                gameThread.moveSnake(2);
                break;
                
            case KeyEvent.VK_A:
                //Va a sinistra
                gameThread.moveSnake(3);
        }
    }//GEN-LAST:event_formKeyPressed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.magube.neuralsnek.snake.JTela tela;
    // End of variables declaration//GEN-END:variables
}
